@echo off
set ANTHROPIC_BASE_URL=http://localhost:20128/v1
set ANTHROPIC_AUTH_TOKEN=sk-aee078f969d013f8-2cb744-2c3ff9ba
set ANTHROPIC_API_KEY=
set ANTHROPIC_MODEL=kr/auto
set ANTHROPIC_SMALL_FAST_MODEL=kr/auto
set CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
claude %*